Kalantari/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # include account urls
    path('account/', include('account.urls', namespace='account')),

    # include workshop urls
    path('', include('workshop.urls', namespace='workshop')),

    # include Product urls
    path('product/', include('product.urls', namespace='product')),

    # include cart urls
    path('cart/', include('cart.urls', namespace='cart')),

    # include Partials urls
    path('partial/', include('partials.urls', namespace='partials'), name='partials'),

    # include Favorite urls
    path('favorite/', include('favorite.urls', namespace='favorite'), name='favorite'),

    # include Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard'), name='dashboard'),

    # include Payments urls
    path('payment/', include('payment.urls', namespace='payment'), name='payment'),
]


# add static_root url to urlpatterns when DEBUG is True
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('_cart/_component/', cart, name='cart'),
    path('item/add/', add_item, name='add_item'),
    path('item/delete/', delete_item, name='delete_item'),
    path('change/count/', change_item_count, name='change_item_count'),
    path('order/info/', get_order_info, name='get_order_info'),
    path('_continue_ordering/', continue_ordering, name='continue_ordering'),
    path('_addressing_package/', addressing_package, name='addressing_package'),
    path('_addressing/_add_address/', add_address, name='add_address'),
    path('_addressing/_delete_address/', delete_address, name='delete_address'),
    path('_check_cart_items/', check_cart_items, name='check_cart_items'),
    path('_receipt/', receipt, name='receipt'),
]

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'

urlpatterns = [
    path('', user_dashboard, name='user_dashboard'),
    path('<path:sub_path>/', user_dashboard, name='user_dashboard_with_sub_path'),
]

workshop/urls.py
from django.urls import path
from .views import *

app_name = 'workshop'

urlpatterns = [
    path('', home_page, name='home_page'),
    path('list/<str:branch>/', ProductListView.as_view(), name='product_list'),
    path('list/woman/', ProductWomanListView.as_view(), name='product_woman_list')
]

templates/parent/base.html
{% extends 'parent/raw.html' %}
{% load static %}
{% load render_partial %}
{% block raw_title %}
    Kalantari | {% block title %}{% endblock %}
{% endblock %}
{% block raw_head %}
    {% include 'parent/head.html' %}
    {% block head %}{% endblock %}
{% endblock %}
{% block raw_content %}
    <div style="display: none">
        {% render_partial 'partials.views.global_cookies' %}
    </div>
    <!-- Loading animation container -->
    <div id="preloader">
        <div id="loader"></div>
    </div>
    {% include 'parent/header.html' %}
    {% block content %}{% endblock %}
    {% include 'parent/footer.html' %}
{% endblock %}

{% block raw_script %}
    <script>
        const isAuthenticated = {% if request.user.is_authenticated %}true{% else %}false{% endif %};
    </script>

    {% include 'parent/script.html' %}
    {% block script %}{% endblock %}
{% endblock %}

templates/parent/footer.html
<footer id="footer">
    <div class="footer">
        <div class="toolbar">
            <div class="f-content about-us">
                <div class="about">
                    <span>درباره ما</span>
                    <p>سبزلرن یک اکادمی خصوصی آموزش برنامه نویسی هست که با هدف تحویل نیروی متخصص بر پایه تولید محتوای
                        غیرسطحی فعالیت میکندسبزلرن یک اکادمی خصوصی آموزش برنامه نویسی هست که با هدف تحویل نیروی متخصص بر
                        پایه تولید محتوای غیرسطحی فعالیت میکندسبزلرن یک اکادمی خصوصی آموزش برنامه نویسی هست که با هدف
                        تحویل نیروی متخصص بر پایه تولید محتوای غیرسطحی فعالیت میکند</p>
                </div>
                <div class="social-media">
                    <a class="svg instagram">
                        <!-- <svg style="color: red" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.<path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" fill="red"></path></svg> -->
                        <svg style="color: white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                            <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                            <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"
                                  fill="white"></path>
                        </svg>
                        <!-- <div class="svg-name">اینستاگرام</div> -->
                    </a>
                    <a class="svg telegram">
                        <!-- <svg style="color: rgb(0, 115, 255)" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"> <path d="M29.919 6.163l-4.225 19.925c-0.319 1.406-1.15 1.756-2.331 1.094l-6.438-4.744-3.106 2.988c-0.344 0.344-0.631 0.631-1.294 0.631l0.463-6.556 11.931-10.781c0.519-0.462-0.113-0.719-0.806-0.256l-14.75 9.288-6.35-1.988c-1.381-0.431-1.406-1.381 0.288-2.044l24.837-9.569c1.15-0.431 2.156 0.256 1.781 2.013z" fill="blue"></path> </svg> -->
                        <svg style="color: white" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32">
                            <path d="M29.919 6.163l-4.225 19.925c-0.319 1.406-1.15 1.756-2.331 1.094l-6.438-4.744-3.106 2.988c-0.344 0.344-0.631 0.631-1.294 0.631l0.463-6.556 11.931-10.781c0.519-0.462-0.113-0.719-0.806-0.256l-14.75 9.288-6.35-1.988c-1.381-0.431-1.406-1.381 0.288-2.044l24.837-9.569c1.15-0.431 2.156 0.256 1.781 2.013z"
                                  fill="white"></path>
                        </svg>
                        <!-- <div class="svg-name">تلگرام</div> -->
                    </a>
                    <a class="svg youtube">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1.63em" height="1.2em" viewBox="0 0 256 180">
                            <path fill="white"
                                  d="M250.346 28.075A32.18 32.18 0 0 0 227.69 5.418C207.824 0 127.87 0 127.87 0S47.912.164 28.046 5.582A32.18 32.18 0 0 0 5.39 28.24c-6.009 35.298-8.34 89.084.165 122.97a32.18 32.18 0 0 0 22.656 22.657c19.866 5.418 99.822 5.418 99.822 5.418s79.955 0 99.82-5.418a32.18 32.18 0 0 0 22.657-22.657c6.338-35.348 8.291-89.1-.164-123.134"/>
                            <path fill="black" d="m102.421 128.06l66.328-38.418l-66.328-38.418z"/>
                        </svg>
                        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="em" viewBox="0 0 256 180"><path fill="white" d="M250.346 28.075A32.18 32.18 0 0 0 227.69 5.418C207.824 0 127.87 0 127.87 0S47.912.164 28.046 5.582A32.18 32.18 0 0 0 5.39 28.24c-6.009 35.298-8.34 89.084.165 122.97a32.18 32.18 0 0 0 22.656 22.657c19.866 5.418 99.822 5.418 99.822 5.418s79.955 0 99.82-5.418a32.18 32.18 0 0 0 22.657-22.657c6.338-35.348 8.291-89.1-.164-123.134"/><path fill="black" d="m102.421 128.06l66.328-38.418l-66.328-38.418z"/></svg> -->
                        <!-- <div class="svg-name">تلگرام</div> -->
                    </a>
                </div>
            </div>
            <div class="list-container">
                <div class="f-list-content footer-menu">
                    <span>دسترسی سریع</span>
                    <div>
                        <a href="">دسته بندی 01</a>
                        <a href="">دسته بندی 02</a>
                        <a href="">دسته بندی 03</a>
                        <a href=""> دسته بندی 04</a>
                        <a href="">دسته بندی 05</a>
                    </div>
                </div>
                <div class="f-list-content footer-menu">
                    <span>تماس با ما</span>
                    <div>
                        <a href="">دسته بندی 01</a>
                        <a href="">دسته بندی 02</a>
                        <a href="">دسته بندی 03</a>
                    </div>
                </div>
            </div>
        </div>
        {#        <div class="social-media2">#}
        {##}
        {#        </div>#}
        <div class="copy-right Oswald-medium">
            <span>Copyright © 2019-2024 Kalantari. All rights reserved.</span>
            <div></div>
        </div>
        <div class="brand">
            <div class="name Cinzel-font">
                <div>K</div>
                <div>A</div>
                <div>L</div>
                <div>A</div>
                <div>N</div>
                <div>T</div>
                <div>A</div>
                <div>R</div>
                <div>I</div>
            </div>
            <!-- <svg width="100%" height="calc(100% + 30%)" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <text x="0" y="100%" textLength="100%" fill="wheat" style="width:100%;font-size:15vw;padding:0px">KALANTARI</text>
            </svg> -->
        </div>
    </div>
</footer>

templates/parent/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/x-icon" href="{% static 'images/main/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/loading.css' %}">

templates/parent/header.html
{% load static %}
{% load render_partial %}
<header>
{#    <img class="background-image" src="{% static 'images/main/back.jpg' %}" alt="">#}
    <div class="header" id="main-header">
        <div class="left">
            <div id="nav-account-btn" class="nav account user-menu-btn">
                <i class="fa-regular fa-user account"></i>
                <!-- <p>حساب کاربری</p> -->
            </div>
            <div id="nav-cart-btn" class="nav cart user-menu-btn">
                <div class="gg-shopping-bag"></div>
                <!-- <i class="fa-solid fa-cart-shopping cart"></i> -->
                <!-- <p>سبد خرید</p>  -->
            </div>
            <div id="nav-favorite-btn" class="nav favorite user-menu-btn">
                <i class="fa-regular fa-star"></i>
                <!-- <div class="gg-shopping-bag"></div> -->
                <!-- <i class="fa-solid fa-cart-shopping cart"></i> -->
                <!-- <p>سبد خرید</p>  -->
            </div>
            <!-- <div class="nav search-bar">
                <i class="fa-solid fa-magnifying-glass"></i>
                <input type="text" placeholder="جستجو">
            </div> -->
        </div>
        <div class="center">
            <span onclick="BrandNameLinkToHomePage()" id="brand-name" class="brand-name Cinzel-font">KALANTARI</span>
        </div>
        <div class="right">
            <div id="menu-btn" class="nav men-btn">
                <p>منو</p>
                <i class="fa-solid fa-bars menu-btn"></i>
            </div>
        </div>
    </div>
    <div id="menu" class="menu" style="direction: rtl">
        <div id="close-menu-btn" class="close-menu-btn">
            <p>بستن</p>
            <i class="fa-solid fa-xmark"></i>
        </div>
        <a href="{% url 'workshop:home_page' %}">خانه</a>
        <a href="{% url 'dashboard:user_dashboard' %}">داشبورد</a>
        <a href="{% url 'dashboard:user_dashboard_with_sub_path' sub_path='/cart/' %}">سبد خرید</a>
        <a href="{% url 'dashboard:user_dashboard_with_sub_path' sub_path='/favorite/' %}">لیست علاقه مندی ها</a>
    </div>
    <div id="user-menu" class="user-menu">
        <div class="sections-container">
            <div id="close-user-menu-btn" class="close-user-menu-btn">
                <i class="fa-solid fa-xmark"></i>
            </div>
            <div class="sections">
                <section id="account-btn" onclick="changeSectionContent('account')" class="section-btn">پروفایل</section>
                <section id="favorite-btn" onclick="changeSectionContent('favorite')" class="section-btn">علاقه مندی</section>
                <section id="cart-btn" onclick="changeSectionContent('cart')" class="section-btn">سبد خرید</section>
            </div>
        </div>
        <div class="sections-content">
            {% render_partial 'partials.views.cart_user_menu' %}
            {% render_partial 'partials.views.favorite_user_menu' %}
            {% render_partial 'partials.views.account_user_menu' %}
        </div>
    </div>
    <div id="overlay" class="overlay">
        <!-- blur -->
    </div>
</header>
<form id="csrf_token" style="display: none;">
    {% csrf_token %}
</form>
<script>
    var header_csrftoken = document.getElementById('csrf_token').children.namedItem('csrfmiddlewaretoken').value;
</script>

templates/parent/raw.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
    <title>{% block raw_title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/raw.css' %}">
    {% block raw_head %}{% endblock %}
</head>
<body>
<div id="log-container">

</div>
{% block raw_content %}{% endblock %}
</body>
<script type="text/javascript" src="{% static 'js/raw.js' %}"></script>
{% block raw_script %}{% endblock %}
</html>

templates/parent/script.html
{% load static %}
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/library/fontawesome.js' %}"></script>
<script src="{% static 'js/header.js' %}"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="{% static 'js/accounting.js' %}"></script>
<!-- axios -->
<script src="{% static 'js/library/axios.js' %}"></script>