Kalantari/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # include account urls
    path('account/', include('account.urls', namespace='account')),

    # include workshop urls
    path('', include('workshop.urls', namespace='workshop')),

    # include Product urls
    path('product/', include('product.urls', namespace='product')),

    # include cart urls
    path('cart/', include('cart.urls', namespace='cart')),

    # include Partials urls
    path('partial/', include('partials.urls', namespace='partials'), name='partials'),

    # include Favorite urls
    path('favorite/', include('favorite.urls', namespace='favorite'), name='favorite'),

    # include Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard'), name='dashboard'),

    # include Payments urls
    path('payment/', include('payment.urls', namespace='payment'), name='payment'),
]


# add static_root url to urlpatterns when DEBUG is True
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('_cart/_component/', cart, name='cart'),
    path('item/add/', add_item, name='add_item'),
    path('item/delete/', delete_item, name='delete_item'),
    path('change/count/', change_item_count, name='change_item_count'),
    path('order/info/', get_order_info, name='get_order_info'),
    path('_continue_ordering/', continue_ordering, name='continue_ordering'),
    path('_addressing_package/', addressing_package, name='addressing_package'),
    path('_addressing/_add_address/', add_address, name='add_address'),
    path('_addressing/_delete_address/', delete_address, name='delete_address'),
    path('_check_cart_items/', check_cart_items, name='check_cart_items'),
    path('_receipt/', receipt, name='receipt'),
]

workshop/urls.py
from django.urls import path
from .views import *

app_name = 'workshop'

urlpatterns = [
    path('', home_page, name='home_page'),
    path('list/<str:branch>/', ProductListView.as_view(), name='product_list'),
    path('list/woman/', ProductWomanListView.as_view(), name='product_woman_list')
]

workshop/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import ListView

from cart.models import Order
from product.models import Product
from tags.models import Branch


# Create your views here.
def home_page(request):
    branchs = Branch.manager.actives()
    context = {
        'branchs': branchs.reverse()
    }
    return render(request, 'workshop/home.html', context)


class ProductListView(ListView):
    model = Product
    template_name = 'workshop/product_list.html'
    paginate_by = 12

    def get_queryset(self):
        branch_name = self.kwargs.get('branch')
        try:
            branch = Branch.manager.actives().get(name=branch_name)
        except Branch.DoesNotExist:
            raise Http404("Category does not exist")
        return Product.published.get_by_branch(branch=branch)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['branch'] = self.kwargs.get('branch')
        return context


class ProductWomanListView(ListView):
    template_name = 'workshop/product_list.html'
    paginate_by = 12

    def get_queryset(self):
        products = Product.published.all()
        if Product is not None:
            return products
        else:
            raise Http404("Product not found")

templates/workshop/home.html
{% extends 'parent/base.html' %}
{% load render_partial %}
{% load static %}
{% block title %}خانه{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}
{% block content %}
    <main class="main">
        <div class="background-video">
            <video id="background-video" autoplay loop muted>
                <source src="{% static 'videos/main/bg-video.mp4' %}" type="video/mp4">
            </video>
            <div class="controls">
                <button id="toggle-play"><i class="fa-solid fa-pause"></i></button>
                <button id="toggle-mute"><i class="fa-solid fa-volume-xmark"></i></button>
            </div>
        </div>
        <div class="categories">
            {% for branch in branchs %}
                <a class="category" href="{{ branch.get_absolute_url }}">
                    <img class="cat-img" src="{{ branch.image.url }}" alt="{{ branch.name }}-category">
                    <div>
                        <strong class="cat-inside-section">{{ branch.title }}</strong>
                        <p class="cat-for-section">برای </p>
                        <!-- <button>دسته بندی بانوان</button> -->
                    </div>
                </a>
            {% endfor %}
            {#            <div class="category woman">#}
            {#                <a class="catinter" href="{% url 'workshop:product_man_list' %}">#}
            {#                    <img src="{% static 'images/main/Womens.webp' %}" alt="womens-category">#}
            {#                    <span>#}
            {#                        <div>#}
            {#                            <strong class="cat-inside-section">بانو</strong>#}
            {#                            <p class="cat-for-section">برای </p>#}
            {#                            <!-- <button>دسته بندی بانوان</button> -->#}
            {#                        </div>#}
            {#                    </span>#}
            {#                </a>#}
            {#            </div>#}
            {#            <div class="category man">#}
            {#                <a class="catinter" href="{% url 'workshop:product_woman_list' %}">#}
            {#                    <span>#}
            {#                        <div>#}
            {#                            <strong class="cat-inside-section">آقا</strong>#}
            {#                            <p class="cat-for-section">برای </p>#}
            {#                            <!-- <button>دسته بندی آقایان</button> -->#}
            {#                        </div>#}
            {#                    </span>#}
            {#                    <img src="{% static 'images/main/Mens.webp' %}" alt="mens-category">#}
            {#                </a>#}
            {#            </div>#}
        </div>

        <!-- <div class="second">
            <p>hello</p>
        </div> -->

        {% render_partial 'partials.views.highest_score_products' %}


    </main>
{% endblock %}
{% block script %}
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

templates/workshop/product_list.html
{% extends 'parent/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}مردانه{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/product_list.css' %}">
{% endblock %}
{% block content %}
<div class="header-black"></div>
	<main class="main">
        <div class="content"></div>
        <div class="items">
            {% for product in page_obj %}
            <a class="product item-link" href="{{ product.get_absolute_url }}">
            {% if product.hover_image %}
            	<div id="{{ product.uid }}" dual-image="true" class="item">
                    <div class="image-container">
                        <img class="cover-image" src="{{ product.cover_image.url }}" alt="{{ product.title }}">
                        <img style="opacity: 0;" src="{{ product.cover_image.url }}" alt="{{ product.title }}">
                        <img class="hover-image" src="{{ product.hover_image.url }}" alt="{{ product.title }}">
                    </div>
                    <div class="item-code">کد کالا: {{ product.uid }}</div>
                    <div class="item-des">
                        <span>{{ product.title | truncatechars:65 | truncatewords:7 }}</span>
                    </div>
                    <div class="item-price-con">
                        <section class="price">
                            {% if product.stock >= 1 %}
                                {{ product.price | intcomma }}
                                <p>تومان</p>
                            {% else %}
                                <span>ناموجود</span>
                            {% endif %} 
                        </section>
                        <button class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>
                    </div>
                </div>
            {% else %}
                <div id="{{ product.uid }}" dual-image="false" class="item">
                    <div class="image-container">
                        <img class="cover-image" src="{{ product.cover_image.url }}" alt="{{ product.title }}">
                        <img style="opacity: 0" src="{{ product.cover_image.url }}" alt="{{ product.title }}">
    {#                    <img class="hover-image" src="{{ product.hover_image.url }}" alt="{{ product.title }}">#}
                    </div>
                    <div class="item-code">کد کالا: {{ product.uid }}</div>
                    <div class="item-des">
                        <span>{{ product.title }}</span>
                    </div>
                    <div class="item-price-con">
                        <section class="price">
                            {{ product.price | intcomma }}
                            <p>تومان</p>
                        </section>
                        <button class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>
                    </div>
                </div>
            {% endif %}
{#            <button onclick="copy_to_clipboard({{ product.get_absolute_url }})" class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>#}
            </a>
            
{#        	{% include 'component/product_item.html' with product=product %}#}
            {% endfor %}
        </div>
        {% include 'component/paginating.html' with page_obj=page_obj %}
    </main>
    {% endblock %}
{% block script %}
    <script src="{% static 'js/product_list.js' %}"></script>
{% endblock %}