Kalantari/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # include account urls
    path('account/', include('account.urls', namespace='account')),

    # include workshop urls
    path('', include('workshop.urls', namespace='workshop')),

    # include Product urls
    path('product/', include('product.urls', namespace='product')),

    # include cart urls
    path('cart/', include('cart.urls', namespace='cart')),

    # include Partials urls
    path('partial/', include('partials.urls', namespace='partials'), name='partials'),

    # include Favorite urls
    path('favorite/', include('favorite.urls', namespace='favorite'), name='favorite'),

    # include Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard'), name='dashboard'),

    # include Payments urls
    path('payment/', include('payment.urls', namespace='payment'), name='payment'),
]


# add static_root url to urlpatterns when DEBUG is True
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register_account, name='register'),
    path('_authenticated/', is_authenticated, name='is_authenticated'),
    path('_dashboard/_profile/', profile_dashboard, name='profile_dashboard'),
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('_cart/_component/', cart, name='cart'),
    path('item/add/', add_item, name='add_item'),
    path('item/delete/', delete_item, name='delete_item'),
    path('change/count/', change_item_count, name='change_item_count'),
    path('order/info/', get_order_info, name='get_order_info'),
    path('_continue_ordering/', continue_ordering, name='continue_ordering'),
    path('_addressing_package/', addressing_package, name='addressing_package'),
    path('_addressing/_add_address/', add_address, name='add_address'),
    path('_addressing/_delete_address/', delete_address, name='delete_address'),
    path('_check_cart_items/', check_cart_items, name='check_cart_items'),
    path('_receipt/', receipt, name='receipt'),
]

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'

urlpatterns = [
    path('', user_dashboard, name='user_dashboard'),
    path('<path:sub_path>/', user_dashboard, name='user_dashboard_with_sub_path'),
]

dashboard/views.py
from django.shortcuts import render


# Create your views here.
def user_dashboard(request, sub_path=None):
    paths = [component for component in sub_path.split('/') if '.' not in component and component != ''] if sub_path is not None else []
    context = {
        'paths': paths
    }
    return render(request, 'dashboard/user_dashboard.html', context)

templates/dashboard/favorite-component.html
{% load static %}

<div class="favorite">
    <ul id="favorite-items-ul" class="items">
    {% if not items%}
    	<div id="empty-favorite">
            <p>هیچ کالایی در لیست شما وجود ندارد.</p>
            <a href="/list/man/">صفحه محصولات</a>
        </div>
    {% endif %}
    <div id="favorite-items-container" class="items-container">
        {% for obj in items %}
            {% with obj.item as item %}
            <li class="item" id="favorite-item-{{ item.product.uid }}">
                <a class="item-info-link" href="{{ item.product.get_absolute_url }}">
                    <img class="item-image" src="{{ item.product.cover_image.url }}" alt="{{ item.product.title }}">
                    <span>کد کالا: {{ item.product.uid }}</span>
                    <p>{{ item.product.title | truncatewords:10 }}</p>
                </a>
                <div id="favorite-item-control-{{ item.product.uid }}" class="favorite-item-control">
                    {% if obj.in_cart == True %}
                        <button id="remove-from-cart-{{ item.product.uid }}" onclick="remove_from_cart({{ item.product.uid }})" class="remove-from-cart" type="button" name="add-to-cart">حذف از سبد خرید</button>
                    {% else %}
                        <button id="add-to-cart-{{ item.product.uid }}" onclick="add_to_cart({{ item.product.uid }})" class="add-to-cart" type="button" name="add-to-cart">افزودن به سبد خرید</button>
                    {% endif %}
                    <section>
                        <button class="share-item" onclick="copy_to_clipboard(`${window.location.origin}{{ item.product.get_absolute_url }}`)" type="button" name="share-item"><i class="fa-solid fa-share-nodes"></i></button>
                        <button onclick="remove_favorite({{ item.product.uid }})" class="remove-from-favorite" type="button" name="remove-item"><i class="fa-solid fa-trash-can"></i></button>
                    </section>
                </div>
            </li>
            {% endwith %}
        {% endfor %}
        
    </div>
    </ul>
</div>

templates/dashboard/profile-component.html
{% if request.user.is_authenticated %}
    <div class="profile">
        <ul class="profile-cards">
            <li class="profile-card">
                <strong>اطلاعات کاربری</strong>
                <div class="card-row name-and-logout">
                    <div class="name-row">
                        <p>نام: </p>
                        <span>{{ full_name }}</span>
                    </div>
                    <button class="logout-btn" type="button" onclick="Logout()">خروج از حساب کاربری</button>
                </div>
                <div class="card-row email-info">
                    <p>آدرس ایمیل شما: </p>
                    <span>{{ email_address }}</span>
                    {% if not email_confirmed %}
                        <span id="email-unverified-warning" style="color: orangered">(تایید نشده!)</span>
                        <button class="disabled">verify</button>
                    {% endif %}
                </div>
                <div class="card-row-con">
                    <div class="card-row">
                        <p>آخرین ورود شما: </p>
                        <span style="direction: ltr">{{ last_login }}</span>
                    </div>
                    <div class="card-row">
                        <p>آخرین آدرس IP شما: </p>
                        <span>{{ last_ip }}</span>
                    </div>
                </div>
            </li>
            <li class="profile-card">
                <stronG></stronG>
            </li>
            <li class="profile-card">
                <stronG></stronG>
            </li>
            <li class="profile-card">
                <stronG></stronG>
            </li>
        </ul>
    </div>
{% else %}
    <div id="first-login-to-your-account">
        <span>ابتدا وارد حساب کاربری خود شوید</span>
        <div class="btns">
            <button onclick="FirstLoginTo()">ورود به حساب</button>
            <div>
                <p>حساب کاربری ندارید؟</p>
                <a href="{% url 'account:register' %}">ایجاد حساب کربری</a>
            </div>
        </div>
    </div>
{% endif %}

templates/dashboard/user_dashboard.html
{% extends 'parent/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="{% static 'css/cart.css' %}">
<link rel="stylesheet" href="{% static 'css/favorite.css' %}">
<link rel="stylesheet" href="{% static 'css/continue_order.css' %}">

<!-- <style>
    .header {
        background-color: black;
    }
    .header.header-hover {
        background-color: white;
    } -->
{% endblock %}
{% block title %}پنل کاربری{% endblock %}
{% block content %}
	
    <main>
        <div class="dashboard-container">
            <div id="section-bar-id" class="section-bar">
                <div id="favorite_section_btn" onclick="chooseSectionBtn(this)" data_section="favorite" class="section">
                    <div class="section-btn">
                        <span>لیست علاقه مندی ها</span>
                    </div>
                    <div class="under-line"></div>
                </div>
                <div id="cart_section_btn" onclick="chooseSectionBtn(this)" data_section="cart" class="section">
                    <div class="section-btn">
                        <span>سبد خرید</span>
                    </div>
                    <div class="under-line"></div>
                </div>
                <div id="profile_section_btn" onclick="chooseSectionBtn(this)" data_section="profile" class="section">
                    <div class="section-btn">
                        <span>پروفایل کاربری</span>
                    </div>
                    <div class="under-line"></div>
                </div>
            </div>
            <div id="content-container" class="content-container">
                <div id="loading-layer" class="layer-container hidden">
                    <div class="loading-layer">
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                        <div class="wave"></div>
                    </div>
                </div>
                <div id="content" class="content">

                </div>
            </div>
        </div>
    </main>
    
{% endblock %}
{% block script %}
<script src="{% static 'js/dashboard.js' %}"></script>
    {{ paths|json_script:'_paths' }}
<script>
    dashboard.paths = JSON.parse(document.getElementById('_paths').textContent);
    dashboard.start(dashboard.paths);
</script>
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/library/axios.js' %}"></script>
<script src="{% static 'js/profile.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
<script src="{% static 'js/favorite.js' %}"></script>
<script src="{% static 'js/continue_order.js' %}"></script>
<script src="{% static 'js/library/jspdf.min.js' %}"></script>
<script src="{% static 'js/library/html2pdf.bundle.min.js' %}"></script>
<script src="{% static 'js/library/jquery-3.6.0.min.js' %}"></script>

<form id="csrf-token">
    {% csrf_token %}
</form>
<script>
    cart.csrfmiddlewaretoken = document.getElementById('csrf-token').children.namedItem('csrfmiddlewaretoken').value;
</script>
{% endblock %}