Kalantari/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # include account urls
    path('account/', include('account.urls', namespace='account')),

    # include workshop urls
    path('', include('workshop.urls', namespace='workshop')),

    # include Product urls
    path('product/', include('product.urls', namespace='product')),

    # include cart urls
    path('cart/', include('cart.urls', namespace='cart')),

    # include Partials urls
    path('partial/', include('partials.urls', namespace='partials'), name='partials'),

    # include Favorite urls
    path('favorite/', include('favorite.urls', namespace='favorite'), name='favorite'),

    # include Dashboard urls
    path('dashboard/', include('dashboard.urls', namespace='dashboard'), name='dashboard'),

    # include Payments urls
    path('payment/', include('payment.urls', namespace='payment'), name='payment'),
]


# add static_root url to urlpatterns when DEBUG is True
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('_cart/_component/', cart, name='cart'),
    path('item/add/', add_item, name='add_item'),
    path('item/delete/', delete_item, name='delete_item'),
    path('change/count/', change_item_count, name='change_item_count'),
    path('order/info/', get_order_info, name='get_order_info'),
    path('_continue_ordering/', continue_ordering, name='continue_ordering'),
    path('_addressing_package/', addressing_package, name='addressing_package'),
    path('_addressing/_add_address/', add_address, name='add_address'),
    path('_addressing/_delete_address/', delete_address, name='delete_address'),
    path('_check_cart_items/', check_cart_items, name='check_cart_items'),
    path('_receipt/', receipt, name='receipt'),
]

dashboard/urls.py
from django.urls import path
from .views import *


app_name = 'dashboard'

urlpatterns = [
    path('', user_dashboard, name='user_dashboard'),
    path('<path:sub_path>/', user_dashboard, name='user_dashboard_with_sub_path'),
]

partials/urls.py
from django.urls import path
from .views import *

app_name = 'render_partials'

urlpatterns = [
    path('global-cookies/', global_cookies, name='global_cookies'),
    path('_user-menu/_account-section', account_user_menu, name='partial-user-menu-account-section'),
    path('_user-menu/_cart-section', cart_user_menu, name='partial-user-menu-cart-section'),
    path('_user-menu/_favorite-section', favorite_user_menu, name='partial-user-menu-favorite-section'),
    path('most/_score/', highest_score_products, name='partial-most-score-products')
]

partials/views.py
import json
import uuid

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render

from cart.views import get_order_info
from core.core.make_data_grouper import make_data_grouper
from cart.models import Order
from favorite.models import Favorite
from product.models import Product


# Create your views here.
def global_cookies(request):
    if request.user.is_authenticated:
        pass
        return JsonResponse({'status': True, 'session_uid': 'authenticated'})
        # items = Order.order_manager.get_order_items(request.user)
    else:
        session_uid = None
        try:
            if not request.session['u_id']:
                request.session['u_id'] = str(uuid.uuid4())
            session_uid = request.session['u_id']
        except KeyError:
            request.session['u_id'] = str(uuid.uuid4())
            session_uid = request.session['u_id']
        return JsonResponse({'status': True, 'session_uid': session_uid})


def account_user_menu(request):
    if request.user.is_authenticated:

        context = {
            'full_name': f'{request.user.first_name} {request.user.last_name}',
        }
        return render(request, 'partial/user-menu-account.html', context)
    else:
        context = {}
        return render(request, 'partial/user-menu-account-login.html', context)


def cart_user_menu(request):
    # if request.user.is_authenticated:
    #     items = Order.order_manager.get_order_items(request.user)
    # else:
    #     session_uid = None
    #     try:
    #         if not request.session['u_id']:
    #             request.session['u_id'] = str(uuid.uuid4())
    #         session_uid = request.session['u_id']
    #     except KeyError:
    #         request.session['u_id'] = str(uuid.uuid4())
    #         session_uid = request.session['u_id']
    #         items = Order.order_manager.get_order_items(request.user)
    items = Order.order_manager.get_order_items(
        user=request.user if request.user.is_authenticated else None,
        session_uid=request.session.get('u_id') if not request.user.is_authenticated else None
    )
    order_info = json.loads(get_order_info(request).content.decode())
    context = {}
    if items:
        context = {
            'empty': False,
            'items': items,
            'price': order_info['price'],
            'discount': order_info['discount'],
            'final_price': order_info['net_price']
        }
    else:
        context = {
            'empty': True,
            'items': items,
            'price': order_info['price'],
            'discount': order_info['discount'],
            'final_price': order_info['net_price']
        }
    return render(request, 'partial/user-menu-cart.html', context)


# @login_required
def favorite_user_menu(request):
    is_authenticated = request.user.is_authenticated
    if is_authenticated:
        items = Favorite.manager.get_favorites(request.user)
    else:
        session_uid = None
        try:
            if not request.session['u_id']:
                request.session['u_id'] = str(uuid.uuid4())
            session_uid = request.session['u_id']
        except KeyError:
            request.session['u_id'] = str(uuid.uuid4())
            session_uid = request.session['u_id']
        items = Favorite.manager.get_favorites(session_uid=session_uid)
    context = {}
    if items:
        context = {
            'empty': False,
            'items': items
        }
    else:
        context = {
            'empty': True,
            'items': items
        }
    return render(request, 'partial/user-menu-favorite.html', context)


def highest_score_products(request):
    products = Product.published.get_highest_score_products(count=12)
    # data = make_data_grouper(4, products)
    context = {
        'products': products
    }
    return render(request, 'partial/highest_score_products.html', context)

templates/partial/highest_score_products.html
{% load static %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'css/most_products.css' %}">
<link rel="stylesheet" href="{% static 'css/library/owl.carousel.css' %}">


<div id="most-products" class="most-products">
    <div id="carousel-container" class="carousel-container owl-carousel">
        {% for product in products %}
            <a class="card item item-link" href="{{ product.get_absolute_url }}">
                <div id="{{ product.uid }}" dual-image="{% if product.hover_image %}true{% else %}false{% endif %}" class="item">
                    <div class="image-container">
                        <img class="cover-image" src="{{ product.cover_image.url }}" alt="{{ product.title }}">
                        <img style="opacity: 0;" src="{{ product.cover_image.url }}" alt="{{ product.title }}">
                        {% if product.hover_image %}
                            <img class="hover-image" src="{{ product.hover_image.url }}" alt="{{ product.title }}">
                        {% endif %} 
                    </div>
                    <div class="item-code">کد کالا: {{ product.uid }}</div>
                    <div class="item-des">
                        <span>{{ product.title | truncatechars:50 | truncatewords:7 }}</span>
                    </div>
                    <div class="item-price-con">
                        <section class="price">
                            {{ product.price | intcomma }}
                            <p>تومان</p>
                        </section>
                        <button class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>
                    </div>
                </div>
    {#           <button onclick="copy_to_clipboard({{ product.get_absolute_url }})" class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>#}
            </a>
        {% endfor %}
        
{#    {% for group in products %}#}
{#    	<div class="carousel-group">#}
{#            {% for product in group %}#}
{#                <a class="card item item-link" href="{{ product.get_absolute_url }}">#}
{#                    <div id="{{ product.uid }}" dual-image="{% if product.hover_image %}true{% else %}false{% endif %}" class="item">#}
{#                        <div class="image-container">#}
{#                            <img class="cover-image" src="{{ product.cover_image.url }}" alt="{{ product.title }}">#}
{#                            <img style="opacity: 0;" src="{{ product.cover_image.url }}" alt="{{ product.title }}">#}
{#                            {% if product.hover_image %}#}
{#                                <img class="hover-image" src="{{ product.hover_image.url }}" alt="{{ product.title }}">#}
{#                            {% endif %} #}
{#                        </div>#}
{#                        <div class="item-code">کد کالا: {{ product.uid }}</div>#}
{#                        <div class="item-des">#}
{#                            <span>{{ product.title }}</span>#}
{#                        </div>#}
{#                        <div class="item-price-con">#}
{#                            <section class="price">#}
{#                                {{ product.price | intcomma }}#}
{#                                <p>تومان</p>#}
{#                            </section>#}
{#                            <button class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>#}
{#                        </div>#}
{#                    </div>#}
    {#            <button onclick="copy_to_clipboard({{ product.get_absolute_url }})" class="share-item-btn" type="button"><i class="fa-solid fa-share-nodes"></i></button>#}
{#                </a>#}
{#            {% endfor %}#}
{#        #}
{#        </div>#}
{#    {% endfor %}#}
    
    </div>
{#<button type="button" class="next-group owl-prev"><i class="fa-solid fa-chevron-right"></i></button>#}
{#<button type="button" class="prev-group owl-next"><i class="fa-solid fa-chevron-left"></i></button>#}
</div>


<script type="text/javascript" src="{% static 'js/most_products.js' %}"></script>
<script type="text/javascript" src="{% static 'js/library/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/library/owl.carousel.js' %}"></script>


















{#<div class="test-main bd-grid owl-carousel">  #}
{#    <article class="card">#}
{#         <div class="card__name">  #}
{#           <p>AIR ZOOM PEGASUS</p>  #}
{#         </div>#}
{#    </article>#}
{#    <article class="card">#}
{#         <div class="card__name">  #}
{#           <p>AIR ZOOM PEGASUS</p>  #}
{#         </div>#}
{#    </article>#}
{#    <article class="card">#}
{#         <div class="card__name">  #}
{#           <p>AIR ZOOM PEGASUS</p>  #}
{#         </div>#}
{#    </article>#}
{#</div>  #}



{#<script>#}
{#$('.owl-carousel').owlCarousel({#}
{#    loop:true,#}
{#    margin: 0,#}
{#    nav:true,#}
{#    items: 1,#}
{#    autoplay:true,#}
{#    autoplayTimeout:4000,#}
{#    autoplayHoverPause:true,#}
    {#responsive:{#}
    {#    0:{ items:1 },#}
    {#    574:{ items:2 },#}
    {#    600:{ items:2 },#}
    {#    800:{ items:3 },#}
    {#    1000:{ items:4 },}}#}
{#</script> #}

templates/partial/user-menu-account-login.html
{% if request.user.is_authenticated %}
    {% include 'partial/user-menu-account.html' %}
{% else %}
    <div id="account" class="container hidden">
        <div class="account-section">
            <div class="authentication-methods">
                <div class="login">
                    <h3>ورود</h3>
                    <p>برای دسترسی به پروفایل خود ابتدا وارد حساب کاربری خود شوید</p>
                    <form id="login-form" class="login-form" action="">
                        {% csrf_token %}
                        <input type="email" name="email" placeholder="ایمیل">
                        <input type="password" name="passwd" placeholder="رمز عبور">
                        <button type="button" name="submit" onclick="Login()">ورود</button>
                    </form>
                </div>
                <div class="qiuck-connect"></div>
                <div class="register-btn">
                    <button id="register-btn" type="button">ثبت نام</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

templates/partial/user-menu-account.html
{% if request.user.is_authenticated %}
    <div id="account" class="container hidden">
        <div class="account-section">
            <div id="profile" class="profile">
                <ul>
                    <li>خوش آمدید  <b>{{ full_name }}</b> .</li>
                    <li class="account-btns">
                        <button class="dash-btn" onclick="GoToDash()">داشبورد</button>
                        <button class="logout-btn" onclick="Logout()">خروج</button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% else %}
    {% include 'partial/user-menu-account-login.html' %}
{% endif %} 

templates/partial/user-menu-cart.html
{% load humanize %}
<div id="cart" class="container hidden">
    <div class="cart-section">
        <div class="cart-box">
            <ul id="cart-user-menu-section-list" class="menu-cart-items">
            {% if items %}
            	{% for item in items %}
                <li id="menu-{{ item.uid }}" class="menu-cart-item">
                    <a href="{{ item.product.get_absolute_url }}" style="text-decoration: none; color: inherit">
                        <img src="{{ item.product.cover_image.url }}" alt="{{ item.product.title }}">
                    </a>
                    <span>{{ item.product.title | truncatewords:5 | truncatechars:50 }}</span>
                    <section id="cart-menu-count-{{ item.uid }}">{{ item.count }}</section>
                    <p>{{ item.price | intcomma }}</p>
                    <form id="form-menu-{{ item.uid }}" action="">
                        {% csrf_token %}
                        <button type="button" name="delete-item" onclick="removeitemfromcart({{ item.uid }})"><i class="fa-solid fa-xmark"></i></button>
                    </form>
                </li>
                {% endfor %}
            {% else %} 
                <li id="cart-menu-empty" class="nothing">هیچ کالایی در سبد خرید شما وجود ندارد.</li>
            {% endif %}
            </ul>
        </div>
    {% if empty %}
        <div class="order-info">
        <div>
            <span>مجموع:</span>
            <span id="details-price">- تومان</span>
        </div>
        <div>
            <span>تخفیف:</span>
            <span id="details-discount">- تومان</span>
        </div>
        <div>
            <span>قیمت نهایی:</span>
            <span id="details-final-price">- تومان</span>
        </div>
    </div>
        <a id="continue-in-cart" href="{% url 'cart:cart' %}" class="continue-in-cart disabled">ادامه در سبد خرید</a>
    {% else %}
            <div class="order-info">
        <div>
            <span>مجموع:</span>
            <span id="details-price">{{ price | intcomma }} تومان</span>
        </div>
        <div>
            <span>تخفیف:</span>
            <span id="details-discount">{{ discount | intcomma }} تومان</span>
        </div>
        <div>
            <span>قیمت نهایی:</span>
            <span id="details-final-price">{{ final_price | intcomma }} تومان</span>
        </div>
    </div>
        <a id="continue-in-cart" href="{% url 'dashboard:user_dashboard_with_sub_path' sub_path='cart' %}" class="continue-in-cart">ادامه در سبد خرید</a>
    {% endif %} 
    </div>
</div>

templates/partial/user-menu-favorite.html
<div id="favorite" class="container hidden">
    <div class="favorite-section">
        <div class="favorite-box">
            <ul id="favorite-user-menu-section-list" class="menu-favorite-items">
            {% if items %}
            	{% for item in items %}
                <li id="menu-favorite-{{ item.product.uid }}" class="menu-favorite-item">
                    <a href="{{ item.product.get_absolute_url }}" style="text-decoration: none; color: inherit;display: flex;flex-direction: row;">
                        <img src="{{ item.product.cover_image.url }}" alt="{{ item.product.title }}">
                        <section class="item-menu-des">
                            <span>{{ item.product.title | truncatechars:65 | truncatewords:7 }}</span>
                            <div class="item-uid">کد کالا: {{ item.product.uid }}</div>
                        </section>
                    </a>
                    <button type="button" name="delete-item" onclick="remove_book_mark({{ item.product.uid }})"><i class="fa-solid fa-xmark"></i></button>
                </li>
                {% endfor %}
            {% else %} 
                <li id="favorite-menu-empty" class="nothing">هیچ کالایی در علاقه مندی ها وجود ندار.</li>
            {% endif %}
            </ul>
        </div>
    {% if empty %}
        <a id="all-favorites" href="{% url 'dashboard:user_dashboard_with_sub_path' sub_path='favorite' %}" class="continue-in-cart disabled">رفتن به علاقه مندی ها</a>
    {% else %}
        <a id="all-favorites" href="{% url 'dashboard:user_dashboard_with_sub_path' sub_path='favorite' %}" class="continue-in-cart">رفتن به علاقه مندی ها</a>
    {% endif %} 
    </div>
</div>